#!/usr/bin/env bash
# copy a file from client to server
# if 4 arguments are given run the scp utility else 'usage: ...'
# 1 - path to file
# 2 - server ip address
# 3 - username scp wants to connect with
# 4- path to SSH private_key files

if [ $# -eq 4 ]
then
	scp -o StrictHostKeyChecking=no -i $4 $1 $3@$2:~  
else
	echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
fi
