#!/usr/bin/env bash
# script to install and start ngnix on a server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo 'Hello World!'>/var/www/html/index.nginx-debian.html
sudo /etc/init.d/nginx start
