#!/usr/bin/bash
# install haproxy using a package manager and configure it to handle

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update
sudo apt-get install -y haproxy=2.5.\*

# write to the haproxy.cfg file
config_lines = "\
frontend haproxy_lb
    bind *:80
    mode http
    default_backend servers

backend servers
    balance roundrobin
    server 121264-web-01 34.232.69.85 check
    server 121264-web-02 52.87.154.146 check
	"
echo 'ENABLE=1'>/etc/haproxy/default
echo "$config_lines" >> /etc/haproxy/haproxy.cfg
