#!/usr/bin/env bash
#4 is bad luck, 8 is ur chance

count=0
while [ $count -lt 10 ]
do
  if [ $count -eq 3 ]
  then
    echo "bad luck"
  elif [ $count -eq 7 ]
  then 
    echo "good luck"
  else 
    echo "Best School"
  fi
  (( count++ ))
done
