#!/usr/bin/env bash
# configure a ufw firewall to block all ports apart from 22, 443 and 80

sudo ufw enable -y
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw status
