#!/usr/bin/env bash
# fix container to run nginx as nginx user listening on port 8080
pkill -f apache2
chmod 644 /etc/nginx/nginx.conf
sed -i "s/user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-enabled/default
su nginx -s /bin/bash -c 'service nginx restart'
