#!/usr/bin/env bash
# fix web_server issue in fewer lines
pkill -f apache2
sed -i "s/#user www-data/user nginx" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-enabled/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
